### ISSUE TITLE
Where is the Transactional boundary?

### ISSUE THREAD

**Issue by sivaprasadreddy** [sofieneBK/hands-on-hexagonal-architecture-with-spring-boot#1]
First of all nice article. But one question.

I don't see anywhere specifying the Transactional boundary using @Transactional. 

Typically in layered architecture we use Service layer as transactional boundary. While following Hex Architecture how do you specify transactional boundary?

**Comment by matheusemm** [comment]
> First of all nice article. But one question.
> 
> I don't see anywhere specifying the Transactional boundary using @transactional.
> 
> Typically in layered architecture we use Service layer as transactional boundary. While following Hex Architecture how do you specify transactional boundary?

Good question. Maybe that configuration could be part of the `application` module, a Spring XML configuration file that declares the transactions boundaries? Not as easy as using `@Transactional` but doable, I guess. It would probably be a pain to try to diferentiate between readonly and read-write transactions in XML, though.

**Comment by sofieneBK** [comment]
> First of all nice article. But one question.
> 
> I don't see anywhere specifying the Transactional boundary using @transactional.
> 
> Typically in layered architecture we use Service layer as transactional boundary. While following Hex Architecture how do you specify transactional boundary?

You can control transactionality at the level of adapter methods. You can include each method in a transaction or add the `@Transactional` annotation in the `BookJpaAdapter` class.

**Comment by sivaprasadreddy** [comment]
In many cases a usecase may perform more than one database operation. In that case having @Transactional on BookJpaAdapter is not correct because each operation run in a different transaction.

**Comment by sofieneBK** [comment]
So use transactional for the specific method you want, that will solve the problem.

**Comment by sivaprasadreddy** [comment]
I know Spring handles transaction if we add @Transactional on any method. But the question is while following Hexagonal Architecture people suggest not to use any framework features in core domain. So I believe transactions should be handled at application layer level and want to know your opinion on it and where would you add transaction boundaries in this sample.

**Comment by sofieneBK** [comment]
Here you are going to add the annotation in the infrastructure part, not to the domain core. the `BookJpaAdapter` class belongs to the infrastructure. so you are free to use all kinds of annotation.

**Comment by sivaprasadreddy** [comment]
Let's take an example of Shoppingcart application. For place an order usecase the flow would be:
```
 API -> InputAdapter -> DomainOrderService.placeOrder(order)
                          -> a)orderRepository.createOrder(order)
                          -> b)customerRepository.saveCustomer(order.getCustomer())
                          -> c)paymentRepository.savePayment(order.getPayment())

```

Here `OrderRepository`, `CustomerRepository`, `PaymentRepository` are outbound port interfaces. You will have `JpaOrderRepositoryAdapter`, `JpaCustomerRepositoryAdapter`, `JpaPaymentRepositoryAdapter` which implement those outbound port interfaces.

The `DomainOrderService.placeOrder(order)` should run in a single transaction. But if you add `@Transactional` to `JpaOrderRepositoryAdapter`, `JpaCustomerRepositoryAdapter`, `JpaPaymentRepositoryAdapter` then all a), b) and c) will run in different transactions.

Hence I think adding `@Transactional` for Outbound Port Adapters is not correct.

**Comment by sofieneBK** [comment]
It is usually a bad idea to have @Transactional declared around repository methods.

Repositories are only for you to access domain entities. Business logic normally involves multiple domain entities and collaborations between them.

In your architecture, you should have a layer to compose business logic. This usually corresponds to a service exposed to external.

This is usually the place you should have your transaction boundary set.

So for your example, the placeOrder method should be inside the infrastructure adapter like the `BookJpaAdapter `which is a service and then you can put the `@Transactional` 

Try to practice it and see how things work.

**Comment by sivaprasadreddy** [comment]
In your example BookJpaAdapter is just one outbound adapter being used from the usecase, but there could be more adapters being used depending on complexity of usecase. In that case we can't wrap everything in one adapter and make it transactional. 

Anyway thanks for sharing your thoughts.

**Comment by sumitsarkar** [comment]
> Let's take an example of Shoppingcart application. For place an order usecase the flow would be:
> 
> ```
>  API -> InputAdapter -> DomainOrderService.placeOrder(order)
>                           -> a)orderRepository.createOrder(order)
>                           -> b)customerRepository.saveCustomer(order.getCustomer())
>                           -> c)paymentRepository.savePayment(order.getPayment())
> ```
> 
> Here `OrderRepository`, `CustomerRepository`, `PaymentRepository` are outbound port interfaces. You will have `JpaOrderRepositoryAdapter`, `JpaCustomerRepositoryAdapter`, `JpaPaymentRepositoryAdapter` which implement those outbound port interfaces.
> 
> The `DomainOrderService.placeOrder(order)` should run in a single transaction. But if you add `@Transactional` to `JpaOrderRepositoryAdapter`, `JpaCustomerRepositoryAdapter`, `JpaPaymentRepositoryAdapter` then all a), b) and c) will run in different transactions.
> 
> Hence I think adding `@Transactional` for Outbound Port Adapters is not correct.

@sivaprasadreddy Did you end up finding a good way to handle this? I am in a similar boat and trying to find a good way to run all the operations in one transaction.

**Comment by sivaprasadreddy** [comment]
I stopped using Clean/Hexagonal Architecture and following https://github.com/sivaprasadreddy/tomato-architecture instead now :-) I shared the reasoning here https://www.sivalabs.in/tomato-architecture-pragmatic-approach-to-software-design/

**Comment by sumitsarkar** [comment]
Thanks for the quick reply @sivaprasadreddy. Had looked at your blog post a month back and hence was curious. Thank you for sharing the post and the repo.

**Comment by brunocassio** [comment]
I know it's an old topic, but for those who are struggling with this situation, my suggestion is:

- If you are using Hexagonal Arch you have probably created a BeanConfiguration Class where you have all services classes.
- If you've done that, try to annotate your beans (Services Classes) with @Transactional.
- this should work and will not break the architecture because the BeanConfiguration Class belongs to the infrastructure layer.

 for example:

`@Bean
@Transactional
    OrderService orderService(OrderRepository orderRepository, CustomerRepository customerRepository, PaymentRepository paymentRepository) {
        return new DomainOrderService(orderRepository, customerRepository, paymentRepository);
    }`

**Comment by edwardduong71311** [comment]
> I know it's an old topic, but for those who are struggling with this situation, my suggestion is:
> 
> * If you are using Hexagonal Arch you have probably created a BeanConfiguration Class where you have all services classes.
> * If you've done that, try to annotate your beans (Services Classes) with [@transactional](https://github.com/transactional).
> * this should work and will not break the architecture because the BeanConfiguration Class belongs to the infrastructure layer.
> 
> for example:
> 
> `@Bean @Transactional OrderService orderService(OrderRepository orderRepository, CustomerRepository customerRepository, PaymentRepository paymentRepository) { return new DomainOrderService(orderRepository, customerRepository, paymentRepository); }`

Nice approach but sometimes they just want to make few methods transactional not a whole class.
